### ISSUE TITLE
dask?!

### ISSUE THREAD

**Issue by pllim** [spacetelescope/acstools#9]
As [reported by Joe here](https://github.com/spacetelescope/acstools/pull/8#issuecomment-235969208)

Also:
```
Processing dependencies for acstools==2.0.3
Searching for dask[array]>=0.5.0
Traceback (most recent call last):
   File "setup.py", line 58, in <module>
     zip_safe=False
   File
".../lib/python2.7/distutils/core.py",
line 151, in setup
     dist.run_commands()
   File
".../lib/python2.7/distutils/dist.py",
line 953, in run_commands
     self.run_command(cmd)
   File
".../lib/python2.7/distutils/dist.py",
line 972, in run_command
     cmd_obj.run()
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/install.py",
line 67, in run
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/install.py",
line 117, in do_egg_install
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/easy_install.py",
line 409, in run
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/easy_install.py",
line 645, in easy_install
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/easy_install.py",
line 696, in install_item
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/easy_install.py",
line 741, in process_distribution
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py",
line 826, in resolve
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py",
line 1092, in best_match
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py",
line 1104, in obtain
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/easy_install.py",
line 652, in easy_install
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/package_index.py",
line 611, in fetch_distribution
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/package_index.py",
line 448, in find_packages
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/package_index.py",
line 782, in scan_url
   File
".../lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/package_index.py",
line 290, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure
to add all dependencies in the meta.yaml
url=https://pypi.python.org/simple/dask/r
+ exit 1
Command failed: /bin/bash -x -e
.../conda_build.sh
```

**Comment by pllim** [comment]
@jhunkeler , what if we change `install_requires` to just `requires` in setup?

**Comment by jhunkeler** [comment]
Apparently `requires` does not conform to the same parsing conventions as `install_requires`:

```
+ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    zip_safe=False
  File "/home/jhunk/anaconda3/envs/_build/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/jhunk/anaconda3/envs/_build/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/dist.py", line 272, in __init__
  File "/home/jhunk/anaconda3/envs/_build/lib/python2.7/distutils/dist.py", line 259, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/home/jhunk/anaconda3/envs/_build/lib/python2.7/distutils/dist.py", line 1220, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/home/jhunk/anaconda3/envs/_build/lib/python2.7/distutils/versionpredicate.py", line 113, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '>=1.0'
+ exit 1
Command failed: /bin/bash -x -e /home/jhunk/anaconda3/conda-bld/work/conda_build.sh
```

**Comment by jhunkeler** [comment]
Reference from basic python installation method:
```
$ python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to acstools.egg-info/requires.txt
writing acstools.egg-info/PKG-INFO
writing top-level names to acstools.egg-info/top_level.txt
writing dependency_links to acstools.egg-info/dependency_links.txt
writing entry points to acstools.egg-info/entry_points.txt
reading manifest file 'acstools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'doc/build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'acstools.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
copying acstools/version.py -> build/lib/acstools
creating build/bdist.macosx-10.6-x86_64/egg
creating build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/__init__.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acs2d.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acs_destripe.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acs_destripe_plus.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acsccd.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acscte.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acsrej.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/acssum.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/calacs.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
creating build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acs2d.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acs2d.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acs_destripe.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acs_destripe.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acs_destripe_plus.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acs_destripe_plus.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acsccd.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acsccd.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acscte.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acscte.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acsrej.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acsrej.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acssum.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/acssum.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/calacs.cfg -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/pars/calacs.cfgspc -> build/bdist.macosx-10.6-x86_64/egg/acstools/pars
copying build/lib/acstools/satdet.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
copying build/lib/acstools/version.py -> build/bdist.macosx-10.6-x86_64/egg/acstools
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acs2d.py to acs2d.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acs_destripe.py to acs_destripe.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acs_destripe_plus.py to acs_destripe_plus.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acsccd.py to acsccd.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acscte.py to acscte.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acsrej.py to acsrej.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/acssum.py to acssum.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/calacs.py to calacs.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/satdet.py to satdet.pyc
byte-compiling build/bdist.macosx-10.6-x86_64/egg/acstools/version.py to version.pyc
creating build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/PKG-INFO -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/entry_points.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/not-zip-safe -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/requires.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
copying acstools.egg-info/top_level.txt -> build/bdist.macosx-10.6-x86_64/egg/EGG-INFO
creating 'dist/acstools-2.0.2.dev9-py2.7.egg' and adding 'build/bdist.macosx-10.6-x86_64/egg' to it
removing 'build/bdist.macosx-10.6-x86_64/egg' (and everything under it)
Processing acstools-2.0.2.dev9-py2.7.egg
creating /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/acstools-2.0.2.dev9-py2.7.egg
Extracting acstools-2.0.2.dev9-py2.7.egg to /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Adding acstools 2.0.2.dev9 to easy-install.pth file
Installing acs_destripe script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing acs_destripe_plus script to /home/jhunk/anaconda3/envs/ugh2/bin

Installed /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/acstools-2.0.2.dev9-py2.7.egg
Processing dependencies for acstools==2.0.2.dev9
Searching for dask[array]>=0.5.0
Reading https://pypi.python.org/simple/dask/
Best match: dask 0.10.2
Downloading https://pypi.python.org/packages/f5/2e/e792722ad02f82344f6edf29aeabb1c918ad41556de8f1a389785415bf85/dask-0.10.2.tar.gz#md5=83da1ea704e3d8bc3492ac55144661c0
Processing dask-0.10.2.tar.gz
Writing /var/folders/vj/19kmn98j1jb84lsk70k1tbv40004m1/T/easy_install-zi5T6H/dask-0.10.2/setup.cfg
Running dask-0.10.2/setup.py -q bdist_egg --dist-dir /var/folders/vj/19kmn98j1jb84lsk70k1tbv40004m1/T/easy_install-zi5T6H/dask-0.10.2/egg-dist-tmp-1BO9_W
no previously-included directories found matching 'docs/_build'
creating /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/dask-0.10.2-py2.7.egg
Extracting dask-0.10.2-py2.7.egg to /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Adding dask 0.10.2 to easy-install.pth file

Installed /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/dask-0.10.2-py2.7.egg
Searching for toolz>=0.7.2
Reading https://pypi.python.org/simple/toolz/
Best match: toolz 0.8.0
Downloading https://pypi.python.org/packages/9e/b0/47e994b3b370087d388d2bb9dfc97c7e901b801265ccd1e8e9fd16eda1b8/toolz-0.8.0.tar.gz#md5=21e051717a14766a4533b6c36bd54575
Processing toolz-0.8.0.tar.gz
Writing /var/folders/vj/19kmn98j1jb84lsk70k1tbv40004m1/T/easy_install-zXgNS_/toolz-0.8.0/setup.cfg
Running toolz-0.8.0/setup.py -q bdist_egg --dist-dir /var/folders/vj/19kmn98j1jb84lsk70k1tbv40004m1/T/easy_install-zXgNS_/toolz-0.8.0/egg-dist-tmp-tX185Z
creating /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/toolz-0.8.0-py2.7.egg
Extracting toolz-0.8.0-py2.7.egg to /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Adding toolz 0.8.0 to easy-install.pth file

Installed /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/toolz-0.8.0-py2.7.egg
Searching for stsci.tools==3.4.1.dev0
Best match: stsci.tools 3.4.1.dev0
Processing stsci.tools-3.4.1.dev0-py2.7.egg
Adding stsci.tools 3.4.1.dev0 to easy-install.pth file
Installing convertlog script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing convertwaiveredfits script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing stscidocs script to /home/jhunk/anaconda3/envs/ugh2/bin

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/stsci.tools-3.4.1.dev0-py2.7.egg
Searching for stsci.imagestats==1.4.1.dev0
Best match: stsci.imagestats 1.4.1.dev0
Processing stsci.imagestats-1.4.1.dev0-py2.7-macosx-10.6-x86_64.egg
Adding stsci.imagestats 1.4.1.dev0 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/stsci.imagestats-1.4.1.dev0-py2.7-macosx-10.6-x86_64.egg
Searching for scipy==0.18.0
Best match: scipy 0.18.0
Adding scipy 0.18.0 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for scikit-image==0.12.3
Best match: scikit-image 0.12.3
Adding scikit-image 0.12.3 to easy-install.pth file
Installing skivi script to /home/jhunk/anaconda3/envs/ugh2/bin

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for numpy==1.11.1
Best match: numpy 1.11.1
Adding numpy 1.11.1 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for astropy==1.2.1
Best match: astropy 1.2.1
Adding astropy 1.2.1 to easy-install.pth file
Installing fitsinfo script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing fitsheader script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing fits2bitmap script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing fitsdiff script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing fitscheck script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing volint script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing wcslint script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing samp_hub script to /home/jhunk/anaconda3/envs/ugh2/bin

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for stsci.distutils==0.3.8.dev0
Best match: stsci.distutils 0.3.8.dev0
Adding stsci.distutils 0.3.8.dev0 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for setuptools==23.0.0
Best match: setuptools 23.0.0
Processing setuptools-23.0.0-py2.7.egg
Adding setuptools 23.0.0 to easy-install.pth file
Installing easy_install script to /home/jhunk/anaconda3/envs/ugh2/bin
Installing easy_install-2.7 script to /home/jhunk/anaconda3/envs/ugh2/bin

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg
Searching for d2to1==0.2.12.post1
Best match: d2to1 0.2.12.post1
Adding d2to1 0.2.12.post1 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for Pillow==3.3.0
Best match: Pillow 3.3.0
Adding Pillow 3.3.0 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for networkx==1.11
Best match: networkx 1.11
Adding networkx 1.11 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Searching for decorator==4.0.9
Best match: decorator 4.0.9
Adding decorator 4.0.9 to easy-install.pth file

Using /Users/jhunk/anaconda3/envs/ugh2/lib/python2.7/site-packages
Finished processing dependencies for acstools==2.0.2.dev9
```

**Comment by jhunkeler** [comment]
```
scikit-image 0.12.3 np111py35_1
-------------------------------
file name   : scikit-image-0.12.3-np111py35_1.tar.bz2
name        : scikit-image
version     : 0.12.3
build number: 1
build string: np111py35_1
channel     : defaults
size        : 17.8 MB
date        : 2016-05-31
fn          : scikit-image-0.12.3-np111py35_1.tar.bz2
license     : 3-clause BSD
license_family: BSD
md5         : b04b674e24288b26839ef00812c23351
priority    : 2
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/scikit-image-0.12.3-np111py35_1.tar.bz2
dependencies:
    matplotlib >=1.3.1
    networkx >=1.8
    numpy 1.11*
    pillow >=2.1
    python 3.5*
    scipy
    six >=1.7.3
```

```
dask 0.10.1 py35_0
------------------
file name   : dask-0.10.1-py35_0.tar.bz2
name        : dask
version     : 0.10.1
build number: 0
build string: py35_0
channel     : defaults
size        : 586 KB
date        : 2016-07-13
fn          : dask-0.10.1-py35_0.tar.bz2
license     : BSD
md5         : 3568c7d96d50a2296f7fe51e62c572fa
priority    : 2
schannel    : defaults
url         : https://repo.continuum.io/pkgs/free/osx-64/dask-0.10.1-py35_0.tar.bz2
dependencies:
    bokeh
    chest
    cloudpickle >=0.2.1
    numpy
    pandas
    partd >=0.3.3
    python 3.5*
    toolz >=0.7.2
```

**Comment by pllim** [comment]
Ugh... that's ugly... I'm making it optional. Will file a PR soon. Thanks for investigating!
